name: "Send Message Simulation MCP"

services:
  server-mcp:
    image: send-message-simulation-mcp:latest
    container_name: send-message-simulation-mcp
    build:
      context: .
      dockerfile: dockerfile
      tags:
        - send-message-simulation-mcp
    restart: unless-stopped
    ports:
      - 8765:8765